POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "ali",
    "password": "admin"
}

###

POST http://127.0.0.1:8000/create_account
Content-Type: application/json

{
    "username": "newuser",
    "password": "qwer/.,m",
    "email": "new@gmail.com"
}

###

GET http://127.0.0.1:8000/test-token
Content-Type: application/json
Authorization: Token 01564cc4e6b74b17a8c3ca1a91a2c15322898b58

###

GET http://127.0.0.1:8000/api/news/

###

GET http://127.0.0.1:8000/api/my-news/

###