# Generated by Django 5.2.7 on 2025-11-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qalampir', '0003_remove_category_description_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
