# Generated by Django 5.2.7 on 2025-11-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qalampir', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube url'),
        ),
    ]
